version: '3' 
networks:
  kafka:
    driver: bridge
 
services:  
  zookeeper:  
    image: wurstmeister/zookeeper  
    ports:  
      - "2181:2181"  
    networks:
      - kafka
      
  kafka:  
    image: wurstmeister/kafka
    ports:  
      - "9092:9092"  
    expose:
      - "9093" 
      
    environment:  
      KAFKA_ADVERTISED_HOST_NAME: localhost  
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_CREATE_TOPICS: "customers:3:1" 
      #  topic:partition:replication factor
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092

    depends_on:
      - zookeeper
    networks:
      - kafka
#    volumes:  
#      - /var/run/docker.sock:/var/run/docker.sock
      
  gradegenerator:  
    image: gradegenerator
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka

  gradestore0:  
    image: gradestore0
    ports:  
      - "8087:8087"  
    depends_on:
      - zookeeper
      - kafka
      - gradegenerator
    networks:
      - kafka

  gradestore1:  
    image: gradestore1
    ports:  
      - "8088:8088"  
    depends_on:
      - zookeeper
      - kafka
      - gradegenerator
    networks:
      - kafka

  gradestore2:  
    image: gradestore2
    ports:  
      - "8089:8089"      
    depends_on:
      - zookeeper
      - kafka
      - gradegenerator
    networks:
      - kafka
      
      
